version: 2.0
jobs:
 build:
   docker:
     - image: circleci/node:10.15.3

   working_directory: ~/repo

   steps:
     - checkout
     - run:
         name: step one >npm install
         command: |
           npm install
           
     - run:
         name: step two >running the test
         command: |
           npm test
          
          